### ISSUE TITLE
UNITY2023.2+WebGLInput  have a error

### ISSUE THREAD

**Issue by oukaichimon** [kou-yeung/WebGLInput#127]
![image](https://github.com/kou-yeung/WebGLInput/assets/30898835/4629cf8e-1116-443b-a53d-4ce57327bf6c)

I upgraded my project from UNITY 2023.1.18 to 2023.2.0. After the upgrade, WebGLInput started throwing errors.

**Comment by oukaichimon** [comment]
I also tried WebGLInput version 1.2, but encountered a similar bug.

**Comment by oukaichimon** [comment]
![image](https://github.com/kou-yeung/WebGLInput/assets/30898835/df7e628d-5e05-4666-94ad-9007ce2596af)
I asked ChatGPT to fix this problem.

I don't know if this is a perfect answer, but my project worked fine.

**Comment by oukaichimon** [comment]
PC版では動きましたが、スマートフォンではエラーを吐いて、動かない（文字入力ができない）状態になりました

**Comment by markv12** [comment]
I am also having this issue:
https://forum.unity.com/threads/webgl-builds-no-longer-run-on-itch-io-after-upgrading-to-unity-2023.1520092/#post-9507913

**Comment by oukaichimon** [comment]
最新版でUNITY2023.2での動作を確認しました
同時にスマホでの動作も確認したのですが、このバージョンを自分のプロジェクトに入れても
エラーが出る事を確認しております

たぶん自分の環境だけで起きているバグで、引き続きなにか解りましたら投稿いたします

**Comment by oukaichimon** [comment]
![image](https://github.com/kou-yeung/WebGLInput/assets/30898835/3dbbdb5b-229e-40c0-aed0-e90ce8df5138)
今のところの自分のプロジェクトでは以下の二箇所をコメントアウトすることで、スマートフォンでも動くのを確認しています
（どうしてそうなったか、なんでそうなるかはまったくわからず）

**Comment by kou-yeung** [comment]
@oukaichimon 
スマホのクラッシュはWebGLInputの不具合ではないようです
Unity2023 の InputField モバイル対応による不具合だと思われます

https://github.com/kou-yeung/WebGLInput/assets/7277282/43236299-2935-44a9-83b3-025c6c57a571

新規プロジェクトで TMP_InputField を配置して WebGLビルドしたら発生しました
上記動画は Chrome の デベロッパーツールでスマホモードにして再現した動画になります

古い InputField では 発生しませんが、
TMP_InputField では Unity公式対応の input element の入力確認後に例外発生しました

WebGLInput がアタッチされた時に、該当TMP_InputFieldを押したら発生する原因は
WebGLInput にも独自の input element を追加してフォーカルするため
WebGLInnputのinput element をフォーカル時に、
Unity製のinput elementからフォーカスが外され「入力確認」と同じ処理が走るから例外発生したと考えられます

**Comment by kou-yeung** [comment]
追加情報として
[公式フォーラム](https://forum.unity.com/threads/keyboard-input-webgl-mobile.505193/page-3#post-9383444)に似てる不具合が報告され

[issue ](https://issuetracker.unity3d.com/issues/error-runtimeerror-null-function-or-function-signature-mismatch-is-thrown-and-the-webgl-player-freezes-when-trying-to-write-text-in-the-input-field-using-mobile-keyboard)には Fixed in 2023.3.0a12 と記載してるため、Unity 2023.3.0a17 で試したら上記動画の例外は解消されました

公式の InputField モバイル対応でWebGLInput のモバイル対応の役目も終わりだと思うから
公式対応されたバージョン以降には WebGLInput の モバイル機能をオフすると思います！
※ PC ブラウザのIME入力は同じく対応されてないため、引き続きメンテナンスが必要ですね orzz

**Comment by kou-yeung** [comment]
[Release](https://github.com/kou-yeung/WebGLInput/releases/tag/1.3.1)
・InputField : from Unity2022.1
・TMP_InputField : from Unity2023.2
上記バージョンではWebGLInputのモバイル対応を無効にして、Unity公式対応を使うようにしました

※モバイルサポートから解放される！(*'▽')
