### ISSUE TITLE
GENIUS!!!

### ISSUE THREAD

**Issue by nsmith1024** [kou-yeung/WebGLInput#2]
It works if the browser canvas is NOT zoomed to full screen.

It dont work if the unity game canvas is zoomed to full screen in the browser.

When in full screen you cant paste anymore, and when you type the text comes out backwards or not at all, seems the cursor stuck at position 0 always.

Oh and im using text edit boxes in a WORLD SPACE canvas instead of SCREEN SPACE.

Can you fix it please?

**Comment by kou-yeung** [comment]
for full screen.i not have idea to fix it.
because fullscreen is work with element of HTML.

i will try support WORLD SPACE.

thanks to report.

**Comment by kou-yeung** [comment]
have a workaround for fullscreen.
you can edit index.html.

1. give a "id" and "size" to webgl-content.
<div class="webgl-content">
↓
<div id="webgl-content" class="webgl-content" style="width: 960px; height: 600px">

2. change fullscreen element target
<div class="fullscreen" onclick="gameInstance.SetFullscreen(1)"></div>
↓
<div class="fullscreen" onclick="document.getElementById('webgl-content').requestFullscreen();"></div>

i add this change to my sample and work.
you can try it.
http://kou-yeung.mygamesonline.org/WebGLInputSample/index.html

**Comment by nsmith1024** [comment]
Thanks so much, i will try it.

**Comment by nsmith1024** [comment]
For others here is the full index.html file

<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Unity WebGL Player | BaseReality</title>
    <link rel="shortcut icon" href="TemplateData/favicon.ico">
    <link rel="stylesheet" href="TemplateData/style.css">
    <script src="TemplateData/UnityProgress.js"></script>  
    <script src="Build/UnityLoader.js"></script>
    <script>
      var gameInstance = UnityLoader.instantiate("gameContainer", "Build/htdocs.json", {onProgress: UnityProgress});
    </script>
  </head>
  <body>
    <div id="webgl-content" class="webgl-content" style="width: 960px; height: 600px">
      <div id="gameContainer" style="width: 960px; height: 600px"></div>
      <div class="footer">
        <div class="webgl-logo"></div>
        <div class="fullscreen" onclick="document.getElementById('webgl-content').requestFullscreen()"></div>
        <div class="title">BaseReality</div>
      </div>
    </div>
  </body>
</html>

**Comment by kou-yeung** [comment]
#8 support WorldSpace Canvas (fix Predictive text position)
this will release next version.

**Comment by CinthiaCuza** [comment]
Hello every one. I'm doing WebGl project in Unity and Kou-Yeung's solution  was great for me. But now I have a problem, because I use a responsive template and I have a button with the functionality FullScreen. With this button in every screen I can maximize or minimize the screen. I have non problem in desktop, the problem is in a mobile with the method document.makeFullscreen('element-name'). I can't minimize or maximize my screen when I want. Are there a solution for this?,  because I want use your solution. Also I want see the function document.makeFullscreen('element-name'),  maybe I can change it for my convenient, but I don't know where is it. It would a pleasure if you can help me.

**Comment by XtroTheArctic** [comment]
We are having consistent backwards typing problem in fullscreen.

I tried this page you shared but it's typing in backwards in fullscreen too.
http://kou-yeung.mygamesonline.org/WebGLInputSample/index.html

Will you be able to fix this backwards typing problem soon?

**Comment by kou-yeung** [comment]
There is no easy way to fix the fullscreen issue.
Because the unity default html template is make the canvas element to fullscreen.
So can not to add a input element overlay.

You can make a iframe to show the builded html.
And make the iframe to fullscreen

FYR : https://unityroom.com/games/webglinput this page is supported fullscreen.

***@***.***

Windows の メ`ル<https://go.microsoft.com/fwlink/?LinkId=550986> から送信

差出人: Onur ***@***.***>
送信日r: 2022年7月23日 2:19
宛先: ***@***.***>
CC: ***@***.***>; State ***@***.***>
件名: Re: [kou-yeung/WebGLInput] GENIUS!!! (#2)


We are having consistent backwards typing problem in fullscreen.

I tried this page you shared but it's typing in backwards in fullscreen too.
http://kou-yeung.mygamesonline.org/WebGLInputSample/index.html

Will you be able to fix this backwards typing problem soon?

―
