### ISSUE TITLE
Uncaught ReferenceError: Runtime is not defined

### ISSUE THREAD

**Issue by xuancelestial** [kou-yeung/WebGLInput#63]
Unity 2021.2.0b4.3123, in line 4 & 9 of WebGLWindow.jslib :

Runtime.dynCall("v", cb, []);

will throw 'Uncaught ReferenceError: Runtime is not defined'.

**Comment by kou-yeung** [comment]
thanks for report!

**Comment by xuancelestial** [comment]
I not sure is it Unity problem or what, but do you have temporarily work-around for this issue? Seems like commenting it will cause the plugin not working

**Comment by kou-yeung** [comment]
maybe emscripten version up at Unity2021.so the Runtime API was removed..
i try to test this issues but has a Known Issues in 2021.2.0b6 "WebGL fails building".
so cann't test it...
please wait....sorry.

**Comment by jdcampbe** [comment]
This is a straight forward fix. For Unity 2021.2+
Some for the JS libs need to be changed so that:
"Runtime.dynCall" -> "dynCall"
and
"Pointer_stringify" to "UTF8ToString"

**Comment by kou-yeung** [comment]
Release a new package support Unity2021.2.0b12
https://github.com/kou-yeung/WebGLInput/releases/tag/1.0

**Comment by juj** [comment]
Instead of calling `Runtime.dynCall("vii", cb, [id, e.shiftKey ? -1 : 1]);`, it is recommended to call `dynCall_vii(cb, id, e.shiftKey ? -1 : 1)`. This form gives better performance than `Runtime.dynCall` or `dynCall`, and should be compatible with both old and new Unity versions.

[In the future](https://github.com/emscripten-core/emscripten/pull/13844) the preferred form will likely be to call `wbind(cb)(id, e.shiftKey ? -1 : 1)`, which will give best performance and generated code size.

**Comment by kou-yeung** [comment]
thanks @juj .

it need to support the old Unity WebGL version (like. Unity 2018)
dynCall_xx and wbind is relatively new api of emscripten?
so. in this time, use Runtime.dynCall or dynCall is better?

It was very helpful.
Thank you for your information
