### ISSUE TITLE
Focus on element

### ISSUE THREAD

**Issue by ohaddahan** [kou-yeung/WebGLInput#97]
We have a chat that pops from the bottom of the screen.
When we use this package, it causes the entire screen to scroll down.
Anyway to disable it?

**Comment by kou-yeung** [comment]
if you just to hide the input element for mobile device.
you can try to comment out "Application.isMobilePlatform"
https://github.com/kou-yeung/WebGLInput/blob/master/Assets/WebGLSupport/WebGLInput/WebGLInput.cs#L162
https://github.com/kou-yeung/WebGLInput/blob/master/Assets/WebGLSupport/WebGLInput/WebGLInput.cs#L189

e.g.
(showHtmlElement || Application.isMobilePlatform);
↓
(showHtmlElement/* || Application.isMobilePlatform*/);

*for mobile device. WebGLInput is force display input element.
because it want to make copy&paste enable for mobile input.

**Comment by kou-yeung** [comment]
it will make input element overlay on the inputfield.
but you cann't select or copy&paste.

**Comment by kou-yeung** [comment]
mobile is support by unity
・InputField : from Unity2022.1
・TMP_InputField : from Unity2023.2

if reproduction at new release. reopen it.
thanks~
